import React, { useState } from "react";
import ReactPaginate from "react-paginate";
import artist from '../public/images/artist.png'
import news from '../public/images/news.png'
import news3 from '../public/images/news3.png'
import aga2 from '../public/images/aga2.png'
import test from '../public/images/test.jpeg'
const Artist = () => {
    const data = {
        cardData: [
          {
            id: 1,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 2,
            img: news,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 3,
            img: news3,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 4,
            img: aga2,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 5,
            img: test,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 6,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 7,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 8,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 10,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 11,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 1,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 12,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 13,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 14,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 15,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 16,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 17,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 18,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 19,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 20,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 21,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 22,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 23,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 24,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 25,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 26,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 27,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 28,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 29,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 30,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 31,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 32,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 33,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 34,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 35,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 36,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 37,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 38,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 39,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 40,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 41,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 42,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 43,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 44,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 45,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 46,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 47,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 48,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },  {
            id: 49,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 50,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 51,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 52,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 53,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 54,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 55,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 56,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 57,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 58,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 59,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 60,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 61,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 62,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 63,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 64,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 65,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 66,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 67,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 68,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 69,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 69,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 70,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 71,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 72,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 73,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 74,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 75,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 76,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 77,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 78,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 79,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 80,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 81,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 82,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 83,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 84,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 85,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 86,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 87,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 88,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 89,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 90,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 91,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 92,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 93,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 94,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 95,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 96,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 97,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 98,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 99,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
          {
            id: 100,
            img: artist,
            title: "Homayoun Sakhi, Rahul Sharma, Salar Nader, Sirojiddin Juraev, Mukhtor Muborakqadomov",
            title2: "In the Footsteps of Babur",
            button: "PURCHASE",
            button2: "CONTACT US",
            body: "In the Footsteps of Babur: Musical Encounters from the Lands of the Mughals",
            des: "Exploring the common ground of musical styles, sensibilities, and the instruments from Central Asia, Afghanistan, and North India, five brilliant instrumentalists illuminate the musical legacy of the Mughal Empire, founded five centuries ago by emperor Babur. ",
          },
         
        ]
        };
        const [users, setUsers] = useState(data.cardData.slice(0, 100));
        const [pageNumber, setPageNumber] = useState(0);
      
        const usersPerPage = 10;
        const pagesvisited = pageNumber * usersPerPage;
      
        const displayUsers = users
          .slice(pagesvisited, pagesvisited + usersPerPage)
          .map((item) => {
            return (
              <div className="sm: px-2 md:px-3 lg:px-8 xl:px-44 2xl:px-60">
                <div className="lg:flex items-start md:flex md:flex-row  py-5 lg:px-10 md:px-5 sm: px-3 justify-center">
                  <div className="md:w-2/5">
                <img className="md:h-72 sm: h-64 w-full " src={item.img} />
                </div>
                  <div className="md:w-3/5 md:ml-5 sm: w-full">
                    <h3 className="text-sm sm: mt-4 md:mt-0">
                    <span className="font-bold pr-2">Artist(s):</span>
                      {item.title}
                    </h3>
                    <h3 className="text-sm mt-3">
                        <span className="font-bold pr-2">Interpretation:</span>
                        {item.title2}
                    </h3>
                    <div className="flex flex-nowrap py-4 md:space-x-7 sm: space-x-4">
                    <div className="group">
                    <button className="group-hover:text-sherpaBlue border border-black bg-darkGreen hover:bg-white text-white rounded-lg md:px-10 sm: px-5 py-1 md:text-sm sm: text-xs font-medium">{item.button}
                        </button>
                        </div>
                        <div className="group">
                        <button className="group-hover:text-white border border-black hover:bg-darkGreen rounded-lg md:px-10 sm: px-5 py-1 md:text-sm sm: text-xs font-medium text-sherpaBlue">{item.button2}</button>
                        </div>
                        </div>
                        <span style={{color: "#323031"}} className="text-xs font-bold">Volume 9</span>
                    <p style={{color: "#323031"}} className="leading-6 text-xs font-semibold text-base">{item.body}</p>
                    <p
                      style={{ color: "#5B5B5B" }}
                      className="md:text-sm sm: text-xs mt-5 leading-5"
                    >
                      {item.des}
                    </p>
                  </div>
                </div>
                <hr className={`border-gray15 `} />
              </div>
            );
          });
        const pageCount = Math.ceil(users.length / usersPerPage);
      
        const changePage = ({ selected }) => {
          setPageNumber(selected);
        };
    return (
        <div>
        <div className="mt-10">{displayUsers}</div>
        <ReactPaginate
          breakLabel={"..."}
          nextLabel={"Next >"}
          pageRangeDisplayed={3}
          marginPagesDisplayed={1}
          pageCount={pageCount}
          onPageChange={changePage}
          containerClassName={"pagination"}
          disabledLinkClassName={""}
          previousClassName={"prevButton"}
         nextLinkClassName={""}
        />
      </div>
    )
}

export default Artist
